### ISSUE TITLE
ip addr

### ISSUE THREAD

**Issue by riccio8** [M0M3NTUM44/Slowris#1]
probably will work for like 5 Min neither, because your IP addr is the same, u should implement a simple change of ip addr, Just for safe reason

**Comment by M0M3NTUM44** [comment]
Agree, I made this for my students, not realy doing anything fancy here, could include some IP cahnges maybe with some cloud based API Gateway.. Thanks

**Comment by riccio8** [comment]
> Agree, I made this for my students, not realy doing anything fancy here, could include some IP cahnges maybe with some cloud based API Gateway.. Thanks

yeah np
